// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Purefolio.DatabaseContext;

namespace Purefolio_backend.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20200910102053_V01_InitialCreate")]
    partial class V01_InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Purefolio.DatabaseContext.Nace", b =>
                {
                    b.Property<int>("NaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("nace_id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("NaceCode")
                        .HasColumnName("nace_code")
                        .HasColumnType("text");

                    b.HasKey("NaceId")
                        .HasName("pk_nace");

                    b.ToTable("nace");
                });

            modelBuilder.Entity("Purefolio.DatabaseContext.NaceRegionData", b =>
                {
                    b.Property<int>("NaceRegionDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("nace_region_data_id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("NaceId")
                        .HasColumnName("nace_id")
                        .HasColumnType("integer");

                    b.Property<int>("RegionId")
                        .HasColumnName("region_id")
                        .HasColumnType("integer");

                    b.Property<string>("corruptionRate")
                        .HasColumnName("corruption_rate")
                        .HasColumnType("text");

                    b.Property<string>("emissionPerYer")
                        .HasColumnName("emission_per_yer")
                        .HasColumnType("text");

                    b.Property<string>("genderPayGap")
                        .HasColumnName("gender_pay_gap")
                        .HasColumnType("text");

                    b.Property<int>("year")
                        .HasColumnName("year")
                        .HasColumnType("integer");

                    b.HasKey("NaceRegionDataId")
                        .HasName("pk_nace_region_data");

                    b.ToTable("nace_region_data");
                });

            modelBuilder.Entity("Purefolio.DatabaseContext.Region", b =>
                {
                    b.Property<int>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("region_id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("RegionCode")
                        .HasColumnName("region_code")
                        .HasColumnType("text");

                    b.HasKey("RegionId")
                        .HasName("pk_region");

                    b.ToTable("region");
                });

            modelBuilder.Entity("Purefolio.DatabaseContext.RegionData", b =>
                {
                    b.Property<int>("RegionDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("region_data_id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("RegionDetailId")
                        .HasColumnName("region_detail_id")
                        .HasColumnType("integer");

                    b.Property<string>("RegionEmission")
                        .HasColumnName("region_emission")
                        .HasColumnType("text");

                    b.HasKey("RegionDataId")
                        .HasName("pk_region_data");

                    b.ToTable("region_data");
                });
#pragma warning restore 612, 618
        }
    }
}
